// A catalog describes one forte2 release: which classes exist, how they
// compose, and what options they take. It is merged from two files:
//   catalog/forte2-<version>.yaml       hand-curated structure and rules
//   catalog/forte2-<version>.dump.json  generated by tools/dump_forte2.py

// An "analysis" node is a post-processing function called on a method after it
// runs, such as a property calculation; nothing follows it.
export type Kind = "system" | "method" | "driver" | "solver" | "value" | "analysis";

export type OptionType =
  | "int"
  | "float"
  | "bool"
  | "str"
  | "text"
  | "enum"
  | "list[int]"
  | "list[float]"
  | "list[str]"
  | "py"
  | "system_ref";

export type Scalar = string | number | boolean | null;

export interface OptionDef {
  type: OptionType;
  values?: Scalar[];
  default?: unknown;
  // Display form of a default that is not JSON (for example a factory object).
  defaultRepr?: string;
  required?: boolean;
  doc?: string;
  advanced?: boolean;
  hidden?: boolean;
  example?: unknown;
  suggest?: string[];
  placeholder?: string;
  // Leave the option out of generated code when any of these options is set.
  unless?: string[];
  // True when the option is not in the curated YAML and was added from the dump.
  uncurated?: boolean;
}

export interface SlotDef {
  accepts: string[];
  required?: boolean;
  many?: boolean;
  positional?: boolean;
  doc?: string;
  advanced?: boolean;
}

// A condition on a value reached through a path such as "self.nel",
// "parent.provides" or "system.x2c.x2c_type".
// "set" treats null, "", false, 0 and empty lists as unset.
export type Condition =
  | Scalar
  | { not: Scalar }
  | { in: Scalar[] }
  | { set: boolean }
  | { has: string }
  | { lacks: string }
  | { gt: number }
  | { range: [number, number] };

export interface Rule {
  when?: Record<string, Condition>;
  require?: Record<string, Condition>;
  require_any?: string[];
  require_one?: string[];
  message: string;
  severity?: "error" | "warning";
  field?: string;
}

export interface NodeDef {
  name: string;
  kind: Kind;
  group: string;
  summary: string;
  import: string;
  api?: string;
  var?: string;
  // Types in the same family can replace each other (RHF and GHF, CISolver
  // and RelCISolver); used by "Switch to" and fix suggestions.
  family?: string;
  abstract?: boolean;
  parents?: string[];
  requires?: string[];
  provides?: string[];
  passes?: string[];
  sets?: Record<string, Scalar>;
  requires_attrs?: Record<string, Scalar>;
  inherit_requirements_from?: string;
  // Python expressions this node offers to the nodes that follow it, keyed by
  // fact; "{self}" stands for this node's variable.
  exprs?: Record<string, string>;
  // Analysis nodes: the function to call, the arguments filled from the
  // upstream method ("{parent}" is its variable, "{parent.<fact>}" one of its
  // exprs), and the variable that holds the printed result.
  call?: string;
  bind?: Record<string, string>;
  result?: string;
  slots: Record<string, SlotDef>;
  options: Record<string, OptionDef>;
  // Options shown on the node card, in order.
  card?: string[];
  rules: Rule[];
  tags?: string[];
}

export interface GroupDef {
  label: string;
  color: string;
}

export interface FactDef {
  label: string;
}

export interface Catalog {
  forte2_version: string;
  docs_base: string;
  groups: Record<string, GroupDef>;
  facts: Record<string, FactDef>;
  attrs: Record<string, Record<string, string>>;
  nodes: Record<string, NodeDef>;
}
