// A catalog describes one forte2 release: which classes exist, how they
// compose, and what options they take. It is merged from two files:
//   catalog/forte2-<version>.yaml       hand-curated structure and rules
//   catalog/forte2-<version>.dump.json  generated by tools/dump_forte2.py

// An "analysis" node is a function or class called on a method after it runs,
// such as a property calculation. Only other analysis nodes can follow it.
export type Kind = "system" | "method" | "driver" | "solver" | "value" | "analysis";

export type OptionType =
  | "int"
  | "float"
  | "bool"
  | "str"
  | "text"
  | "enum"
  | "list[int]"
  | "list[float]"
  | "list[str]"
  | "py"
  | "system_ref";

export type Scalar = string | number | boolean | null;

export interface OptionDef {
  type: OptionType;
  values?: Scalar[];
  default?: unknown;
  // Display form of a default that is not JSON (for example a factory object).
  defaultRepr?: string;
  required?: boolean;
  doc?: string;
  advanced?: boolean;
  hidden?: boolean;
  example?: unknown;
  suggest?: string[];
  placeholder?: string;
  // Leave the option out of generated code when any of these options is set.
  unless?: string[];
  // True when the option is not in the curated YAML and was added from the dump.
  uncurated?: boolean;
}

export interface SlotDef {
  accepts: string[];
  required?: boolean;
  many?: boolean;
  positional?: boolean;
  doc?: string;
  advanced?: boolean;
}

// A condition on a value reached through a path such as "self.nel",
// "self.ci_params.ci_algorithm", "parent.provides", "parent.final_orbitals",
// "parent.ci_solver.type" or "system.x2c.x2c_type".
// "set" treats null, "", false, 0 and empty lists as unset. "not" takes one
// value or a list of values. "gt" and "lt" take a number or another path.
export type Condition =
  | Scalar
  | { not: Scalar | Scalar[] }
  | { in: Scalar[] }
  | { set: boolean }
  | { has: string }
  | { lacks: string }
  | { gt: number | string }
  | { lt: number | string }
  | { range: [number, number] };

export interface Rule {
  when?: Record<string, Condition>;
  require?: Record<string, Condition>;
  require_any?: string[];
  require_one?: string[];
  message: string;
  severity?: "error" | "warning";
  field?: string;
}

export interface NodeDef {
  name: string;
  kind: Kind;
  group: string;
  summary: string;
  import: string;
  api?: string;
  var?: string;
  // Types in the same family can replace each other (RHF and GHF, CISolver
  // and RelCISolver); used by "Switch to" and fix suggestions.
  family?: string;
  abstract?: boolean;
  parents?: string[];
  requires?: string[];
  provides?: string[];
  passes?: string[];
  sets?: Record<string, Scalar>;
  requires_attrs?: Record<string, Scalar>;
  // The slot holding the object this node hands its work to (a driver's
  // solver). The node must meet that object's requires_attrs, and passes its
  // sets downstream.
  delegates_to?: string;
  // Python expressions this node offers to the nodes that follow it, keyed by
  // fact; "{self}" stands for this node's variable and "{parent.<fact>}" for
  // an expression of this node's own upstream.
  exprs?: Record<string, string>;
  // Where the node's electron count comes from, for the parity checks forte2
  // runs when the node binds to a System.
  electrons?: Electrons;
  // Analysis nodes: the function or class to call, the arguments filled from
  // the upstream node ("{parent}" is its variable, "{parent.<fact>}" one of
  // its expressions), and the variable that holds the result.
  call?: string;
  bind?: Record<string, string>;
  result?: string;
  // What the script prints for an analysis result: false for nothing, or an
  // expression ("{self}" is the result). The result itself when omitted.
  print?: false | string;
  slots: Record<string, SlotDef>;
  options: Record<string, OptionDef>;
  // Options shown on the node card, in order.
  card?: string[];
  rules: Rule[];
  tags?: string[];
}

// The electron count is the System's nuclear charge minus the option named by
// `charge`. `ms` names the spin-projection option, if any.
export interface Electrons {
  charge: string;
  ms?: string;
  closed_shell?: boolean;
}

export interface GroupDef {
  label: string;
  color: string;
}

export interface FactDef {
  label: string;
  // The expression for this fact on a node that doesn't define its own in
  // exprs; "{self}" stands for the node's variable.
  expr?: string;
}

export interface Release {
  tag: string;
  url: string;
}

export interface Catalog {
  forte2_version: string;
  // The forte2 release this catalog describes.
  release?: Release;
  docs_base: string;
  groups: Record<string, GroupDef>;
  facts: Record<string, FactDef>;
  attrs: Record<string, Record<string, string>>;
  nodes: Record<string, NodeDef>;
}
