import { useMemo, useState, type ReactNode } from "react";
import { useStore } from "../store";
import { generatePython } from "../codegen/python";
import { Icon } from "./Icon";

const TOKEN =
  /("""[\s\S]*?"""|"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*')|(#.*)|\b(from|import|as|None|True|False)\b|\b(\d+\.?\d*(?:e-?\d+)?)\b|([A-Z][A-Za-z0-9_]*)(?=\()|([a-z_][a-z0-9_]*)(?==)/g;

function highlight(code: string): ReactNode[] {
  const out: ReactNode[] = [];
  let last = 0;
  let k = 0;
  for (const m of code.matchAll(TOKEN)) {
    if (m.index > last) out.push(code.slice(last, m.index));
    const cls = m[1] ? "tk-str" : m[2] ? "tk-com" : m[3] ? "tk-kw" : m[4] ? "tk-num" : m[5] ? "tk-cls" : "tk-arg";
    out.push(
      <span key={k++} className={cls}>
        {m[0]}
      </span>,
    );
    last = m.index + m[0].length;
  }
  out.push(code.slice(last));
  return out;
}

export function useGeneratedCode(): string {
  const doc = useStore((s) => s.doc);
  const catalog = useStore((s) => s.catalog);
  const meta = useStore((s) => s.meta);
  return useMemo(() => {
    const title = meta.title ? `${meta.title}\n` : "";
    return generatePython(doc, catalog, {
      header: `${title}Generated by forte2 builder for forte2 ${catalog.forte2_version}.`,
    });
  }, [doc, catalog, meta.title]);
}

export function CodePanel() {
  const code = useGeneratedCode();
  const analysis = useStore((s) => s.analysis);
  const meta = useStore((s) => s.meta);
  const [copied, setCopied] = useState(false);
  const lines = code.split("\n");
  if (lines[lines.length - 1] === "") lines.pop();
  // Highlight line by line, carrying open triple-quoted strings across lines.
  let inString = false;
  const rendered = lines.map((line) => {
    const quotes = line.split('"""').length - 1;
    if (inString) {
      if (quotes % 2 === 1) inString = false;
      return <span className="tk-str">{line}</span>;
    }
    if (quotes % 2 === 1) {
      inString = true;
      const at = line.indexOf('"""');
      return (
        <>
          {highlight(line.slice(0, at))}
          <span className="tk-str">{line.slice(at)}</span>
        </>
      );
    }
    return highlight(line);
  });

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 1400);
    } catch {
      // Clipboard access can be refused; the code is still selectable.
    }
  };

  const download = () => {
    const blob = new Blob([code], { type: "text/x-python" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${(meta.title ?? "forte2_input").replace(/[^A-Za-z0-9]+/g, "_").toLowerCase()}.py`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="code-panel">
      <div className="code-bar">
        {analysis.errors > 0 ? (
          <span className="code-status bad">
            <Icon name="alert" size={13} /> {analysis.errors} error{analysis.errors === 1 ? "" : "s"} to fix
            before this runs
          </span>
        ) : (
          <span className="code-status ok">
            <Icon name="check" size={13} /> Passes the builder's checks
          </span>
        )}
        <span className="spacer" />
        <button className="btn ghost small" onClick={copy}>
          <Icon name={copied ? "check" : "copy"} size={13} /> {copied ? "Copied" : "Copy"}
        </button>
        <button className="btn ghost small" onClick={download}>
          <Icon name="download" size={13} /> .py
        </button>
      </div>
      <pre className="code">
        <code>
          {lines.map((_, i) => (
            <div key={i} className="code-line">
              <span className="ln">{i + 1}</span>
              <span>{rendered[i]}</span>
            </div>
          ))}
        </code>
      </pre>
    </div>
  );
}
